### PR TITLE
Updated some of the content

### PR DESCRIPTION
**Pull request by duttakapil**
I haven't updated all of the content yet. We need to add Firebase or Airtable to the form at the bottom, to save the submissions and select the candidates. 

Any critique, other than the obvious content changes that need to be made. 

Demo : https://duttakapil.github.io/month-of-code/

### CODE REVIEW

**Comment by vramana** [comment]
image

**Comment by duttakapil** [comment]
Think it's a problem with Blink. Gecko renders it properly 
Firefox : 
image

**Comment by vramana** [comment]
But we still have to fix it regardless.

**Comment by duttakapil** [comment]
Do you have a clue how to fix it? I don't.

**Comment by vramana** [comment]
Even I don't 😄. I'll look into later.

**Comment by duttakapil** [comment]
Then let's merge and fix it later?

**Review by vramana — APPROVED** [review]

**Comment by vinaypuppal** [comment]
@vramana Can you change color of `<select/>` or `<option/>` in css to `black` and see if text is visible? I am not able to reproduce it on my OSX chrome since browser uses O.S select box by default try above in your O.S and check if it works

**Comment by duttakapil** [comment]
@vinaypuppal let's move this to https://github.com/fcc-hyd/month-of-code/issues/2

**Pull request merged**
